services:
  php-app:
    deploy:
      replicas: 3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./public:/var/www/public
      - ./apache-vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./storage:/var/www/storage
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    entrypoint: /bin/bash -c "/var/www/tailwind.sh && /var/www/composer.sh && apache2-foreground"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-app
volumes:
  storage:
  public:
