services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./storage:/var/www/storage
    container_name: unreal-asset-store
volumes:
  storage:
